on:
  push:
    branches:
      - ma






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    -uses: actions/checkout@v3
      
    - name: "login to docker hub"
      run: docker login --username basant9 --password dckr_pat_LHJuHMGKEBrr97zZ5jrl_CFI8vc
      