on:
  push:
    branches:
      - ma






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
    - name: 'Testing Github action'
      run: pwd
    - name: 'Testing Github action'
      run: echo Ahmed
